### ISSUE TITLE
Script für Primärzuweisung

### ISSUE THREAD

**Issue by mari-fu-berlin** [mari-fu-berlin/omeka#12]
Der Objekttyp Shared Object hat ein Metadatenfeld "Sigle konstituierende Nachricht"; auf dieser Grundlage sollte eine Objekt-Beziehung des Typs Primärzuweisung programmatisch vorgenommen werden. Schön wäre dafür eine neue Schaltfläche in Mari Verwaltung.

Als Autor der Zuweisung sollte der Nutezr "projekt" eingetragen werden (schon angelegt)
Als Annotation sollte eingetragen werden: "Primärzuweisung, beim Ingest von Katalogdaten vorgenommen."

Überprüfung und Korrekturmöglichkeit wie bei den Autocomplete-Feldern

**Comment by grandgeorg** [comment]
erledigt
