### ISSUE TITLE
Autocomplete für Item Relations

### ISSUE THREAD

**Issue by mari-fu-berlin** [mari-fu-berlin/omeka#13]
Bei Aufruf des Tabs Objekt-Beziehungen von Objekt bearbeiten soll die Möglichkeit bestehen, die Objekt ID über ein Autocomplete-Feld zu wählen. Quelle sind zunächst Objekte des Objekttyps Shared Object. Später wird es auch Item Relations geben, bei denen die Quellen Ort, Raum oder Gebäude sind.

**Comment by grandgeorg** [comment]
resolved by 6317600856f356b8a854c472a053f45da80505f3 and 049f38a847a30329198f784fd2c1f7585f09ad1b
